#!/usr/bin/env bash

if [[ -s "/home/deploy/.rvm/environments/ruby-2.0.0-p247@findsyou" ]]
then
  source "/home/deploy/.rvm/environments/ruby-2.0.0-p247@findsyou"
  exec sidekiq "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/deploy/.rvm/environments/ruby-2.0.0-p247@findsyou'" >&2
  exit 1
fi
